---

- name: All apt related stuff
  hosts: laptop
  become: true
  tasks:
  - name: Install apt packages
    ansible.builtin.apt:
      pkg:
      - htop
      - neovim
      - tmux 
      - zsh

  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: Cleanup 
    ansible.builtin.apt:
      autoremove: true
