---
- hosts: all
  become: true

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include_tasks: tasks/user.yml
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/apt-install.yml
    - include_tasks: tasks/apt-upgrade.yml
    - include_tasks: tasks/flatpak-install.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/fstab.yml
    - include_tasks: tasks/nvim.yml
    - include_tasks: tasks/tmux.yml
    - include_tasks: tasks/thunderbird.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/tabby.yml
    - include_tasks: tasks/gnome.yml
    - include_tasks: tasks/install-nerdfonts.yml
    - include_tasks: tasks/python-package.yml
