---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include_tasks: tasks/user.yml
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/apt-update.yml
    - include_tasks: tasks/apt-upgrade.yml
    - include_tasks: tasks/flatpak-install.yml
    - include_tasks: tasks/zsh.yml
 
