---

- name: Apt-upgrade
  ansible.builtin.apt:
      update_cache: true
      upgrade: true

- name: Install apt packages
  ansible.builtin.apt:
    pkg:
    - htop
    - neovim
    - nfs-common 
    - cmake
    - gettext
    - bat
    state: present

- name: Uninstall non-required package
  ansible.builtin.apt:
    pkg:
    - nodejs
    state: absent

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Cleanup 
  ansible.builtin.apt:
    autoremove: true
