---

- name: nodejs - Downloading nodeJS setup script
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/setup_current.x
    dest: ~/nodesource_setup.sh 
    mode: +x
  tags: nodejs

- name: nodejs - Running nodeJS install script
  ansible.builtin.shell: bash ~/nodesource_setup.sh
  tags: nodejs
 
- name: nodejs - Install nodeJS
  ansible.builtin.apt:
    pkg:
      - nodejs
  tags: nodejs
