---

- name: Load variables
  include_vars: ../vars/vars.yml

- name: neovim | remove vim packages via apt if it exists
  become: true
  ansible.builtin.apt:
    name: vim
    state: absent

- name: neovim | install nvim via apt
  become: true
  ansible.builtin.apt:
    name: neovim
    state: latest 

- name: ensures the nvim folder exists to drop the config
  file: 
    path: /home/{{ username }}/.config/nvim 
    state: directory
  become_user: jeremy

- name: Copying neovim config 
  ansible.builtin.copy:
    src: ../files/.config/nvim/
    dest: /home/{{ username }}/.config/nvim
  become_user: jeremy
