---

- name: Install pip
  ansible.builtin.apt:
    pkg:
    - python3
    - python3-pip
    state: present
  when: ansible_os_family == "Debian"

- name: Install pip and Python packages on MacOS
  ansible.builtin.homebrew:
    name:
    - python3
  become: false
  when: ansible_os_family == "Darwin"

- name: Install standard python package that are typically needed
  ansible.builtin.pip:
    name:
    - ipykernel 
    - notebook
    - pre-commit

