---

- name: Install pip
  ansible.builtin.apt:
    pkg:
    - python3
    - python3-pip
    state: present

- name: Install standard python package that are typically needed
  ansible.builtin.pip:
    name:
    - ipykernel 
    - notebook
    - pre-commit

