---
- name: Load variables
  include_vars: ../vars/vars.yml

- name: Ensure ssh directory exists.
  ansible.builtin.file:
    dest: "~/.ssh/"
    mode: 0700
    state: directory

- name: Copy private SSH keys
  ansible.builtin.copy:
    src: "../files/.ssh/id_ed25519"
    dest: "/home/{{ username }}/.ssh/id_ed25519"

- name: Copy public SSH keys
  ansible.builtin.copy:
    src: "../files/.ssh/id_ed25519.pub"
    dest: "/home/{{ username }}/.ssh/id_ed25519.pub"

- name: Set permissions on SSH private key
  ansible.builtin.file:
    path: "/home/{{ username }}/.ssh/id_ed25519"
    state: file
    mode: "0600"
  become: true

