---

- name: Install Mozilla Thunderbird
  community.general.flatpak:
    name:
      - org.mozilla.Thunderbird
    method: system 
    state: present

- name: Define profile variable
  set_fact:
    profile: 9acjnte4.default-release

- name: ensures the thunderbird folder exists to drop the config in
  file: 
    path: /home/{{ username }}/.thunderbird/{{ profile }}/
    state: directory

- name: Copying thunderbird profile config
  ansible.builtin.copy:
    src: ../files/.thunderbird/logins.json
    dest: /home/{{ username }}/.thunderbird/{{ profile }}/logins.json


