---

- name: Load variables
  include_vars: ../vars/vars.yml

- name: Install tmux
  ansible.builtin.apt:
    name: tmux
    state: present

- name: Copying tmux config 
  ansible.builtin.copy:
    src: ../files/.tmux.conf
    dest: /home/{{ username }}/.tmux.conf
  become_user: jeremy 

- name: Clone Tmux Plugin Manager
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "{{ home_directory }}/.tmux/plugins/tpm"
  become_user: jeremy
