---

- name: Apt-upgrade (Linux)
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  when: ansible_os_family == "Debian"

- name: Homebrew upgrade (macOS)
  homebrew:
    update_homebrew: yes
    upgrade: true
  when: ansible_os_family == "Darwin"
  become: false  # Ensure Homebrew tasks do not use sudo

