---

- name: Load variables
  include_vars: ../vars/vars.yml

- name: Checking if oh-my-zsh is installed
  stat:
    path: "{{ home_directory }}/.oh-my-zsh"
  register: zsh_install_directory

- name: Downloading oh-my-zsh
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: ~/install-ohmyzsh.sh
    mode: +x
  when: zsh_install_directory.stat.exists == false
  register: install_ohmyzsh

- name: Installing oh-my-zsh
  command: ~/install-ohmyzsh.sh
  when: zsh_install_directory.stat.exists == false

- name: Deleting oh-my-zsh install.sh
  file:
    path: ~/install-ohmyzsh.sh
    state: absent

- name: Install zsh syntax highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: ~/.oh-my-zsh/custom  

- name: Install zsh autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: ~/.oh-my-zsh/custom  

- name: Copying .zshrc file
  template:
    src: ../files/.zshrc
    dest: "{{ home_directory }}/.zshrc"

- name: Make zsh the default shell
  user:
    name: "{{ username }}"
    shell: "/bin/zsh"
